config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'
  devise_for :users

  namespace :welcome do
    get :index
    get :build_invoices
  end

  resources :cash_flows, except: [:show]
  resources :invoices, except: [:show]
  namespace :invoices do
    resource :batchs, only: [:new, :create]
  end
  resources :members, except: [:show, :destroy] do
    resources :invoices, except: [:show, :destroy], controller: 'members/invoices'
    resources :cash_flows, except: [:show, :destroy], controller: 'members/cash_flows'
  end

  namespace :reports do
    namespace :invoices do
      get :paid
    end
    namespace :cash_flows do
      get :monthly
    end
  end
end

app/models/concerns/invoices/category.rb
module Invoices
  module Category
    extend ActiveSupport::Concern

    included do
      enum category: {
        membership: 'membership',
        surcharge: 'surcharge'
      }
    end
  end
end

app/models/invoice.rb
# == Schema Information
#
# Table name: invoices
#
#  id              :bigint           not null, primary key
#  category        :string           not null
#  reference_date  :date
#  reference_month :integer
#  reference_year  :integer
#  value           :float            not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  cash_flow_id    :bigint
#  member_id       :bigint
#
# Indexes
#
#  index_invoices_on_cash_flow_id  (cash_flow_id)
#  index_invoices_on_member_id     (member_id)
#  index_invoices_once_per_month   (member_id,reference_month,reference_year) UNIQUE
#
class Invoice < ApplicationRecord
  include Invoices::Category

  belongs_to :member
  belongs_to :cash_flow, optional: true

  validates :category, :value, :reference_date, presence: true

  scope :paid, -> { where('cash_flow_id IS NOT NULL') }
  scope :on_month, lambda { |date = Time.zone.today|
    where('reference_date BETWEEN :begin AND :end', begin: date.beginning_of_month, end: date.end_of_month)
  }
  scope :on_year, lambda { |date = Time.zone.today|
    where('reference_date BETWEEN :begin AND :end', begin: date.beginning_of_year, end: date.end_of_year)
  }
  scope :overdue, lambda {
    where(cash_flow_id: nil)
      .where('reference_date < :date', date: Time.zone.today.beginning_of_month)
  }

  def paid?
    cash_flow_id.present?
  end

  def formated_reference_month
    format('%02d', reference_date.month)
  end
end

app/controllers/invoices/batchs_controller.rb
module Invoices
  class BatchsController < AuthenticatedController
    def new
      default_attr = {
        category: :membership,
        reference_date: Time.zone.today
      }
      @invoice = Invoice.new(default_attr)
    end

    def create
      params.require(:invoice).permit(:category, :reference_date).to_h

      Member.active.all.each do |member|
        invoice_params = permitted_params.merge({ member:, value: member.membership_value })

        Invoice.find_or_create_by(invoice_params)
      end

      redirect_to invoices_path
    end

    private

    def permitted_params
      params.require(:invoice).permit(:category, :reference_date).to_h
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < AuthenticatedController
  before_action :find_invoice, only: %i[edit update destroy]

  def index
    params[:q] ||= {}
    params[:p] ||= {}
    params[:s] ||= ['created_at desc']

    @q = InvoiceInteractor::List.call(params.permit!).data
    @pagy, @invoices = pagy(@q.result)
  end

  def new
    default_attr = {
      category: :membership,
      reference_date: Time.zone.today
    }

    @invoice = Invoice.new(default_attr)
  end

  def create
    result = InvoiceInteractor::Create.call(params: permitted_params)

    if result.success?
      create_success_notice
      redirect_to invoices_path
    else
      @invoice = result.invoice
      build_error_alert
      render :new
    end
  end

  def edit; end

  def update
    result = InvoiceInteractor::Update.call(invoice: @invoice, params: permitted_params)

    if result.success?
      update_success_notice
      redirect_to invoices_path
    else
      @invoice = result.invoice
      build_error_alert
      render :edit
    end
  end

  def destroy
    @invoice.destroy ? delete_success_notice : build_error_alert

    redirect_to invoices_path
  end

  private

  def build_error_alert
    flash[:alert] = @invoice.errors.map(&:full_message)
  end

  def find_invoice
    @invoice = Invoice.find(params[:id])
  end

  def permitted_params
    params.require(:invoice).permit(:category, :value, :reference_date, :cash_flow_id,
                                    :member_id).to_h
  end
end

app/controllers/members/invoices_controller.rb
module Members
  class InvoicesController < AuthenticatedController
    before_action :find_invoice, only: %i[edit update destroy]

    def index
      params[:q] ||= {}
      params[:p] ||= {}
      params[:s] ||= ['created_at desc']
      @member_id = params.require(:member_id).to_i

      @pagy, @invoices = pagy(Invoice.where(member_id: @member_id), items: 10)
      # InvoiceInteractor::List.call(params.permit!)
    end

    def new
      default_attr = {
        value: Member.find(params[:member_id]).membership_value,
        category: :membership,
        reference_date: Time.zone.today
      }.merge(params.permit(:member_id).to_h)

      @invoice = Invoice.new(default_attr)
    end

    def create
      result = InvoiceInteractor::Create.call(params: permitted_params)

      if result.success?
        create_success_notice
        redirect_to member_invoices_path(member_id: result.invoice.member_id)
      else
        @invoice = result.invoice
        build_error_alert
        render :new
      end
    end

    def edit; end

    def update
      result = InvoiceInteractor::Update.call(invoice: @invoice, params: permitted_params)

      if result.success?
        update_success_notice
        redirect_to member_invoices_path(member_id: result.invoice.member_id)
      else
        @invoice = result.invoice
        build_error_alert
        render :edit
      end
    end

    def destroy
      @invoice.destroy ? delete_success_notice : build_error_alert

      redirect_to invoices_path
    end

    private

    def build_error_alert
      flash[:alert] = @invoice.errors.map(&:full_message)
    end

    def find_invoice
      @invoice = Invoice.find(params[:id])
    end

    def permitted_params
      params.require(:invoice).permit(:category, :value, :reference_date, :cash_flow_id,
                                      :member_id).to_h
    end
  end
end

app/controllers/reports/invoices_controller.rb
module Reports
  class InvoicesController < AuthenticatedController
    def paid
      @format = params[:format]
      @year = params.require(:year)
      @result = ReportInteractor::Invoices::Paid.call(year: params.require(:year))

      respond_to do |format|
        format.html
        format.pdf do
          render pdf: 'invoices_paid', orientation: 'Landscape', layout: 'pdf', formats: [:html]
        end
      end
    end
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def invoice_cash_flows(member_id)
    CashFlow.input.invoiced.where(member_id:).map do |cash_flow|
      ["#{l(cash_flow.moved_at, format: :long)} - R$ #{cash_flow.value.to_f.round(2)}", cash_flow.id]
    end
  end

  def invoice_members
    Member.active.map { |member| [member.name, member.id] }
  end

  def invoice_category_options
    Invoice.categories.keys.map do |key|
      [Invoice.human_attribute_name("category.#{key}"), key]
    end
  end
end

app/views/invoices/_form.html.erb
<div class="row">
  <div class="col-md-6 mb-3">
    <%= form.label Member.model_name.human, class: 'form-label' %>
    <%= form_select(:member_id, invoice_members, form)%>
  </div>
  <div class="col-md-6 mb-3">
    <%= form.label CashFlow.model_name.human, class: 'form-label' %>
    <%= form_select(:cash_flow_id, invoice_cash_flows(@invoice.member_id), form)%>
  </div>
  <div class="col-md-6 mb-3">
    <%= form.label :category, class: 'form-label' %>
    <%= form_select(:category, invoice_category_options, form)%>
  </div>
  <div class="col-md-6 mb-3">
    <%= form.label :value, class: 'form-label' %>
    <div class="input-group mb-3">
      <span class="input-group-text">R$</span>
      <%= form.number_field :value, step: 0.01, class: 'form-control' %>
    </div>
  </div>
  <div class="col-md-6 mb-3">
    <%= form.label :reference_date, class: 'form-label' %>
    <%= form.date_field :reference_date, class: 'form-control' %>
  </div>
</div>

app/views/invoices/_search.html.erb
<button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#search-modal">
  <i class="bi bi-search"></i>
  <%= t('helpers.submit.search') %>
</button>
<div class="modal fade" id="search-modal" tabindex="-1" aria-labelledby="search-modal-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= search_form_for @q do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="search-modal-label"><%= t('helpers.submit.search') %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-12 mb-3">
              <%= form.label Member.model_name.human, class: 'form-label' %>
              <%= form_select(:member_id_eq, invoice_members, form)%>
            </div>
            <div class="col-md-12 mb-3">
              <%= form.label :category_eq, class: 'form-label' %>
              <%= form_select(:category_eq, invoice_category_options, form)%>
            </div>
            <div class="col-md-6 mb-3">
              <%= form.label :reference_date_eq, class: 'form-label' %>
              <%= form.date_field :reference_date_eq, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= link_to 'Limpar', invoices_path, class: 'btn btn-outline-secondary' %>
          <%= form.submit t('helpers.submit.search'), :class  => "btn btn-md btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/invoices/edit.html.erb
<% content_for :title, t('.title') %>
<h3><%= t('.title') %></h3>

<%= form_with model: @invoice, method: :patch do |form| %>
  <%= render partial: 'form', locals: { form: form } %>
  <%= form.submit t('helpers.submit.update', model: Invoice.model_name.human), :class  => "btn btn-md btn-primary" %>
<% end %>

app/views/invoices/index.html.erb
<% content_for :title, t('.title') %>
<h3><%= t('.title') %></h3>

<div class="row">
  <div class="col-md-4 mb-3">
    <%= render partial: 'search' %>
  </div>
  <div class="col-md-8 mb-3 text-end">
    <%= link_to new_invoices_batchs_path, class: 'btn btn-outline-secondary' do %>
      Criar em lote
    <% end %>
    <%= link_to new_invoice_path(member_id: @member_id), class: 'btn btn-primary' do %>
      <i class="bi bi-plus"></i>
      <%= t('helpers.new') %>
    <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-hover table-bordered align-middle caption-bottom">
    <thead class="table-light">
      <tr>
        <th scope="col"><%= Member.model_name.human %></th>
        <th scope="col"><%= Invoice.human_attribute_name('category') %></th>
        <th scope="col"><%= Invoice.human_attribute_name('reference_date') %></th>
        <th scope="col"><%= Invoice.human_attribute_name('value') %></th>
        <th scope="col">Pago?</th>
        <th scope="col"><%= t('helpers.actions') %></th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <% @invoices.each do |invoice| %>
        <tr>
          <td><%= invoice.member.name %></td>
          <td><%= Invoice.human_attribute_name("category.#{invoice.category}") %></td>
          <td><%= l(invoice.reference_date) %></td>
          <td><%= number_to_currency(invoice.value, locale: :'pt-BR') %></td>
          <td><%= invoice.cash_flow_id.present? ? 'Sim' : 'Não' %></td>
          <td>
            <div class="btn-toolbar" role="toolbar">
              <%= link_to edit_invoice_path(invoice.id), class: 'btn btn-outline-primary btn-sm me-1' do %>
                <i class="bi bi-pencil"></i>
              <% end %>
              <%= button_to invoice_path(invoice.id), method: :delete,
                    form: {data: {turbo_confirm: 'Are you sure?'}}, class: 'btn btn-outline-danger btn-sm' do %>
                <i class="bi bi-trash3"></i>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
    <%= render partial: 'layouts/pagination' %>
  </table>
</div>

app/views/invoices/new.html.erb
<% content_for :title, t('.title') %>
<h3><%= t('.title') %></h3>

<%= form_with model: @invoice, method: :post do |form| %>
  <%= render partial: 'form', locals: { form: form } %>
  <%= form.submit t('helpers.submit.create', model: Invoice.model_name.human), :class  => "btn btn-md btn-primary" %>
<% end %>