config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'
  devise_for :users

  namespace :welcome do
    get :index
    get :build_invoices
  end

  resources :cash_flows, except: [:show]
  resources :invoices, except: [:show]
  namespace :invoices do
    resource :batchs, only: [:new, :create]
  end
  resources :members, except: [:show, :destroy] do
    resources :invoices, except: [:show, :destroy], controller: 'members/invoices'
    resources :cash_flows, except: [:show, :destroy], controller: 'members/cash_flows'
  end

  namespace :reports do
    namespace :invoices do
      get :paid
    end
    namespace :cash_flows do
      get :monthly
    end
  end
end

app/models/cash_flow.rb
# == Schema Information
#
# Table name: cash_flows
#
#  id          :bigint           not null, primary key
#  category    :string           not null
#  description :string
#  kind        :string           not null
#  moved_at    :date             not null
#  value       :float            not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  member_id   :bigint
#
# Indexes
#
#  index_cash_flows_on_member_id  (member_id)
#
class CashFlow < ApplicationRecord
  include CashFlows::Kind
  include CashFlows::Category

  belongs_to :member

  has_many :invoices, dependent: :restrict_with_exception

  validates :kind, :category, :value, presence: true

  scope :invoiced, -> { not_donation.not_revenue }

  def self.balance
    input.sum(:value) - output.sum(:value)
  end
end

app/models/concerns/cash_flows/category.rb
module CashFlows
  module Category
    extend ActiveSupport::Concern

    included do
      enum category: {
        membership: 'membership',
        donation: 'donation',
        other: 'other',
        mission: 'mission',
        revenue: 'revenue'
      }
    end

    def input_categories
      %i[membership donation revenue other]
    end

    def output_categories
      %i[mission other]
    end
  end
end

app/models/concerns/cash_flows/kind.rb
module CashFlows
  module Kind
    extend ActiveSupport::Concern

    included do
      enum kind: {
        input: 'input',
        output: 'output'
      }
    end
  end
end

app/controllers/cash_flows_controller.rb
class CashFlowsController < AuthenticatedController
  before_action :find_cash_flow, only: %i[edit update destroy]

  def index
    params[:q] ||= {}
    params[:p] ||= {}
    params[:s] ||= ['date asc']

    @q = CashFlowInteractor::List.call(params.permit!).data
    @pagy, @cash_flows = pagy(@q.result)
  end

  def new
    @cash_flow = CashFlow.new
  end

  def create
    result = CashFlowInteractor::Create.call(params: permitted_params)

    if result.success?
      create_success_notice
      redirect_to cash_flows_path
    else
      @cash_flow = result.cash_flow
      build_error_alert
      render :new
    end
  end

  def edit; end

  def update
    result = CashFlowInteractor::Update.call(cash_flow: @cash_flow, params: permitted_params)

    if result.success?
      update_success_notice
      redirect_to cash_flows_path
    else
      @cash_flow = result.cash_flow
      build_error_alert
      render :edit
    end
  end

  def destroy
    @cash_flow.destroy ? delete_success_notice : build_error_alert

    redirect_to cash_flows_path
  end

  private

  def build_error_alert
    flash[:alert] = @cash_flow.errors.map(&:full_message)
  end

  def find_cash_flow
    @cash_flow = CashFlow.find(params[:id])
  end

  def permitted_params
    params.require(:cash_flow).permit(:category, :kind, :value, :member_id, :moved_at, :description).to_h
  end
end

app/controllers/members/cash_flows_controller.rb
module Members
  class CashFlowsController < AuthenticatedController
    before_action :find_cash_flow, only: %i[edit update destroy]

    def index
      params[:q] ||= {}
      params[:p] ||= {}
      params[:s] ||= ['date asc']

      @pagy, @cash_flows = pagy(CashFlow.all, items: 10)
      # CashFlowInteractor::List.call(params.permit!)
    end

    def new
      @cash_flow = CashFlow.new
    end

    def create
      result = CashFlowInteractor::Create.call(params: permitted_params)

      if result.success?
        create_success_notice
        redirect_to cash_flows_path
      else
        @cash_flow = result.cash_flow
        build_error_alert
        render :new
      end
    end

    def edit; end

    def update
      result = CashFlowInteractor::Update.call(cash_flow: @cash_flow, params: permitted_params)

      if result.success?
        update_success_notice
        redirect_to cash_flows_path
      else
        @cash_flow = result.cash_flow
        build_error_alert
        render :edit
      end
    end

    def destroy
      @cash_flow.destroy ? delete_success_notice : build_error_alert

      redirect_to cash_flows_path
    end

    private

    def build_error_alert
      flash[:alert] = @cash_flow.errors.map(&:full_message)
    end

    def find_cash_flow
      @cash_flow = CashFlow.find(params[:id])
    end

    def permitted_params
      params.require(:cash_flow).permit(:category, :kind, :value, :member_id, :moved_at).to_h
    end
  end
end

app/controllers/reports/cash_flows_controller.rb
module Reports
  class CashFlowsController < AuthenticatedController
    def monthly
      @format = params[:format]
      @date = params.require(:date).to_date
      @result = ReportInteractor::CashFlows::Monthly.call(month: format('%02d', @date.month), year: @date.year)

      respond_to do |format|
        format.html
        format.pdf do
          render pdf: 'cash_flow_monthly', layout: @layout, formats: [:html]
        end
      end
    end
  end
end

app/helpers/cash_flows_helper.rb
module CashFlowsHelper
  def cash_flow_kind_options
    CashFlow.kinds.keys.map do |key|
      [CashFlow.human_attribute_name("kind.#{key}"), key]
    end
  end

  def cash_flow_category_options
    CashFlow.categories.keys.map do |key|
      [CashFlow.human_attribute_name("category.#{key}"), key]
    end
  end

  def cash_flow_members
    Member.active.map { |member| [member.name, member.id] }
  end
end

app/views/cash_flows/_form.html.erb
<div class="row">
  <div class="col-md-6 mb-3">
    <%= form.label :category, class: 'form-label' %>
    <%= form_select(:category, cash_flow_category_options, form)%>
  </div>
  <div class="col-md-6 mb-3">
    <%= form.label :kind, class: 'form-label' %>
    <%= form_select(:kind, cash_flow_kind_options, form)%>
  </div>
  <div class="col-md-6 mb-3">
    <%= form.label Member.model_name.human, class: 'form-label' %>
    <%= form_select(:member_id, cash_flow_members, form)%>
  </div>
  <div class="col-md-6 mb-3"></div>
  <div class="col-md-6 mb-3">
    <%= form.label :moved_at, class: 'form-label' %>
    <%= form.date_field :moved_at, class: 'form-control', max: 0.days.after %>
  </div>
  <div class="col-md-6 mb-3">
    <%= form.label :value, class: 'form-label' %>
    <div class="input-group mb-3">
      <span class="input-group-text">R$</span>
      <%= form.number_field :value, step: 0.01, class: 'form-control' %>
    </div>
  </div>
  <div class="col-md-6 mb-3">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>
</div>

app/views/cash_flows/_search.html.erb
<button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#search-modal">
  <i class="bi bi-search"></i>
  <%= t('helpers.submit.search') %>
</button>
<div class="modal fade" id="search-modal" tabindex="-1" aria-labelledby="search-modal-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="search-modal-label"><%= t('helpers.submit.search') %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= search_form_for @q do |form| %>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-12 mb-3">
              <%= form.label Member.model_name.human, class: 'form-label' %>
              <%= form_select(:member_id_eq, cash_flow_members, form)%>
            </div>
            <div class="col-md-6 mb-3">
              <%= form.label :kind_eq, class: 'form-label' %>
              <%= form_select(:kind_eq, cash_flow_kind_options, form)%>
            </div>
            <div class="col-md-6 mb-3">
              <%= form.label :category_eq, class: 'form-label' %>
              <%= form_select(:category_eq, cash_flow_category_options, form)%>
            </div>
            <div class="col-md-6 mb-3">
              <%= form.label :moved_at_gteq, class: 'form-label' %>
              <%= form.date_field :moved_at_gteq, class: 'form-control' %>
            </div>
            <div class="col-md-6 mb-3">
              <%= form.label :moved_at_lteq, class: 'form-label' %>
              <%= form.date_field :moved_at_lteq, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= link_to 'Limpar',cash_flows_path, class: 'btn btn-outline-secondary' %>
          <%= form.submit t('helpers.submit.search'), :class  => "btn btn-md btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cash_flows/edit.html.erb
<% content_for :title, t('.title') %>
<h3><%= t('.title') %></h3>

<%= form_with model: @cash_flow, method: :patch do |form| %>
  <%= render partial: 'form', locals: { form: form } %>
  <%= form.submit t('helpers.submit.update', model: CashFlow.model_name.human), :class  => "btn btn-md btn-primary" %>
<% end %>

app/views/cash_flows/index.html.erb
<% content_for :title, t('.title') %>
<h3><%= t('.title') %></h3>
  
<div class="row">
  <div class="col-md-4 mb-3">
    <%= render partial: 'search' %>
  </div>
  <div class="col-md-8 mb-3 text-end">
    <%= link_to new_cash_flow_path, class: 'btn btn-primary' do %>
      <i class="bi bi-plus"></i>
      <%= t('helpers.new') %>
    <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-hover table-bordered align-middle caption-bottom">
    <thead class="table-light">
      <tr>
        <th scope="col"><%= Member.model_name.human %></th>
        <th scope="col"><%= CashFlow.human_attribute_name('kind') %></th>
        <th scope="col"><%= CashFlow.human_attribute_name('category') %></th>
        <th scope="col"><%= CashFlow.human_attribute_name('moved_at') %></th>
        <th scope="col"><%= CashFlow.human_attribute_name('value') %></th>
        <th scope="col"><%= CashFlow.human_attribute_name('description') %></th>
        <th scope="col"><%= t('helpers.actions') %></th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <% @cash_flows.each do |cash_flow| %>
        <tr>
          <td><%= cash_flow.member.name %></td>
          <td><%= CashFlow.human_attribute_name("kind.#{cash_flow.kind}") %></td>
          <td><%= CashFlow.human_attribute_name("category.#{cash_flow.category}") %></td>
          <td><%= l(cash_flow.moved_at, format: :long) %></td>
          <td><%= number_to_currency(cash_flow.value, locale: :'pt-BR')  %></td>
          <td><small><%= cash_flow.description %></small></td>
          <td>
            <div class="btn-toolbar" role="toolbar">
              <%= link_to edit_cash_flow_path(cash_flow.id), class: 'btn btn-outline-primary btn-sm me-1' do %>
                <i class="bi bi-pencil"></i>
              <% end %>
              <%= button_to cash_flow_path(cash_flow.id), method: :delete,
                    form: {data: {turbo_confirm: 'Are you sure?'}}, class: 'btn btn-outline-danger btn-sm' do %>
                <i class="bi bi-trash3"></i>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
    <%= render partial: 'layouts/pagination' %>
  </table>
</div>

app/views/cash_flows/new.html.erb
<% content_for :title, t('.title') %>
<h3><%= t('.title') %></h3>

<%= form_with model: @cash_flow, method: :post do |form| %>
  <%= render partial: 'form', locals: { form: form } %>
  <%= form.submit t('helpers.submit.create', model: CashFlow.model_name.human), :class  => "btn btn-md btn-primary" %>
<% end %>