config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'
  devise_for :users

  namespace :welcome do
    get :index
    get :build_invoices
  end

  resources :cash_flows, except: [:show]
  resources :invoices, except: [:show]
  namespace :invoices do
    resource :batchs, only: [:new, :create]
  end
  resources :members, except: [:show, :destroy] do
    resources :invoices, except: [:show, :destroy], controller: 'members/invoices'
    resources :cash_flows, except: [:show, :destroy], controller: 'members/cash_flows'
  end

  namespace :reports do
    namespace :invoices do
      get :paid
    end
    namespace :cash_flows do
      get :monthly
    end
  end
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="alert alert-success d-flex align-items-center" role="alert">
    <i class="bi bi-check-circle-fill"></i>
    <div>
      <%= notice %>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger d-flex align-items-center" role="alert">
    <i class="bi bi-exclamation-triangle-fill"></i>
    <div class="container">
      <% if alert.is_a?(Array) %>
        <%= t('errors.template.body') %>
        <div class="container">
          <% alert.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </div>
      <% else %>
        <%= alert %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container">
    <%= link_to root_path, class: 'navbar-brand' do %>
    <%= image_tag("RedhawksBrasaoPB.png", height: '38', width: '32') %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to Member.model_name.human(count: 2), members_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to CashFlow.model_name.human(count: 2), cash_flows_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to Invoice.model_name.human(count: 2), invoices_path, class: 'nav-link' %>
        </li>
        <%# <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li> %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_pagination.html.erb
<% if @pagy.pages > 1 %>
  <caption>
    <%== pagy_bootstrap_nav(@pagy) %>
  </caption>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('application.title') %> - <%= yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>

    <div class="container mt-3">
      <%= render partial: 'layouts/alerts' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "application" -%>
    <%= wicked_pdf_javascript_include_tag "application" -%>
    <style>
      /* table { display : inline-block} */
      /* thead { display: table-row-group } */
      /* tfoot { display: table-row-group } */
      /* tr { page-break-inside: avoid }

      .page-break {
          display:block; clear:both; page-break-after:always;
      } */
      table, tr, td, th, tbody, thead, tfoot {
        page-break-inside: avoid !important;
      }
  </style>
  </head>
  <body>
    <div id="header">
      <% wicked_pdf_image_tag image_url('RedhawksBrasaoPB.png'), { height: '38', width: '32' } %>
      <h1><%= yield :title %></h1>
    </div>
    <br/>
    <div id="content" style="border: none;">
      <%= yield %>
    </div>
  </body>
</html>